# Generated by Django 5.0.3 on 2024-03-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس ', 'verbose_name_plural': 'تماس ها'},
        ),
    ]
